spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Challenge
    username: root
    password: Rocobz16
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
